<?php

namespace frontend\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\NklHistoryInfo;

/**
 * Team: @NKL,NKU
 * Coding by 李力铤 1711345
 * NklHistoryInfoSearch represents the model behind the search form of `app\models\NklHistoryInfo‘ generated by gii.
 */

class NklHistoryInfoSearch extends NklHistoryInfo
{
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['history_id'], 'integer'],
            [['history_title', 'history_passage'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = NklHistoryInfo::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'history_id' => $this->history_id,
        ]);

        $query->andFilterWhere(['like', 'history_title', $this->history_title])
            ->andFilterWhere(['like', 'history_passage', $this->history_passage]);

        return $dataProvider;
    }
}
