<?php

namespace frontend\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * Team: @NKL,NKU
 * Coding by 朱心怡 1711304
 * This is the model class for table "product" generated by gii.
 */

class Products extends ActiveRecord
{
    public static function tableName()
    {
        return 'nkl_products_info';
    }
}