<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
/**
 * Team: @NKL,NKU
 * Coding by 李伟 1711350
 * This is the bbs search for the activities views generated by gii.
 */
/* @var $this yii\web\View */
/* @var $model common\models\NklBbsInfoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="nkl-bbs-info-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'bbs_id') ?>

    <?= $form->field($model, 'bbs_time') ?>

    <?= $form->field($model, 'bbs_userNickname') ?>

    <?= $form->field($model, 'bbs_userDescribe') ?>

    <?= $form->field($model, 'bbs_content') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
