<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
/**
 * Team: @NKL,NKU
 * Coding by 李伟 1711350
 * This is the activities form for the activities views generated by gii.
 */

/* @var $this yii\web\View */
/* @var $model common\models\NklActivityInfo */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="nkl-activity-info-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'activity_info')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'activity_location')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'activity_beginDate')->textInput() ?>

    <?= $form->field($model, 'activity_beginTime')->textInput() ?>

    <?= $form->field($model, 'activity_endDate')->textInput() ?>

    <?= $form->field($model, 'activity_endTime')->textInput() ?>

    <?= $form->field($model, 'activity_hostDept')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
