<?php

use yii\helpers\Html;
/**
 * Team: @NKL,NKU
 * Coding by 李伟 1711350
 * This is the activities create for the activities views generated by gii.
 */

/* @var $this yii\web\View */
/* @var $model common\models\NklActivityInfo */

$this->title = 'Create Nkl Activity Info';
$this->params['breadcrumbs'][] = ['label' => 'Nkl Activity Infos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="nkl-activity-info-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
