<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
/**
 * Team: @NKL,NKU
 * Coding by 李伟 1711350
 * This is the activities view for the activities views generated by gii.
 */
/* @var $this yii\web\View */
/* @var $model common\models\NklActivityInfo */

$this->title = $model->activity_id;
$this->params['breadcrumbs'][] = ['label' => 'Nkl Activity Infos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="nkl-activity-info-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->activity_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->activity_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'activity_id',
            'activity_info',
            'activity_location',
            'activity_beginDate',
            'activity_beginTime',
            'activity_endDate',
            'activity_endTime',
            'activity_hostDept',
        ],
    ]) ?>

</div>
