<?php
namespace frontend\controllers;
use yii\web\Controller;
/**
 * Team: @NKL,NKU
 * Coding by 朱心怡 1711304
 * NklProductsInfo Controller implements the CRUD actions for NklBbsInfo model generated by gii.
 */
class NklproductsinfoController extends Controller{
    public function actionIndex(){
    $this->layout = false;
    return $this->render("index");
    }


    public function actionPayment($productname){
    $new = $productname;
    $this->layout = false;
    return $this->render("payment",['new'=>$new]);
    }


    public function actionSucceed(){

    $this->layout = false;
    return $this->render("succeed");
    }
    public $enableCsrfValidation = false;
}
